#!/usr/bin/env bash
# ⚖️ LBH — Editor consciente de referencias externas

REF_PATH="contracts/external_refs/GEMINI_HANDSHAKE.ref.lbh"

mkdir -p "$(dirname "$REF_PATH")"

if [ ! -f "$REF_PATH" ]; then
  cat << 'TEMPLATE' > "$REF_PATH"
[LBH-EXTERNAL-REF]
REF_NAME=GEMINI_HANDSHAKE
REF_TYPE=AI_MODEL
TRUST_LEVEL=EXTERNAL_CONTROLLED
CHAIN_POLICY=READ_ONLY

[SIGNATURE]
SIGNED_BY=LBH_MASTER
SIGNATURE_METHOD=DETERMINISTIC_HASH
SIGNATURE_HASH=PENDING
TEMPLATE
fi

nano "$REF_PATH"
